### ISSUE TITLE
working/488.org [PL markup, mm.]

### ISSUE THREAD

**Issue by syssel** [Clara-Kloster/Guldkorpus#145]
- [ ] På linje [201](https://github.com/Clara-Kloster/Guldkorpus/blame/master/transcriptions/org/working/488.org#L201) har \<lm\>-linjen overtaget kolonnerne fra den følgende \<w\>-linje, der står tom.
- [ ] Linje 201 og 202, forkert rækkefølge (bør byttes om)? Se henvisning til manuskriptets linjenummer for begge linjer.
- [ ] \<PL\>.e på linje [204](https://github.com/Clara-Kloster/Guldkorpus/blame/master/transcriptions/org/working/488.org#L204) mangler et begyndende \<PL\>.b-tag

**Comment by syssel** [comment]
Hej Rasmus! @Osodanes 
Jeg håber at det er okay at jeg assigner dig til de småfejl, jeg finder i transskriptionerne, som jeg ikke selv kan rette.

**Comment by Osodanes** [comment]
Hej Sidsel, @syssel , det er bare i orden :D
