### ISSUE TITLE
working/481.org [PE markup]

### ISSUE THREAD

**Issue by syssel** [Clara-Kloster/Guldkorpus#147]
- [ ] \<PE\>-tagget der starter på linje [75](https://github.com/Clara-Kloster/Guldkorpus/blame/master/transcriptions/org/working/481.org#L75) mangler et sluttag.

**Comment by Osodanes** [comment]
Hmm, end tag is present, but after the ad. Don't know if has to be nested within the ad tags?

**Comment by syssel** [comment]
Ah, right. Hm. Then everything should be alright, but for some reason the test catches it -- which it shouldn't! I will take a look at it :)

**Comment by syssel** [comment]
@Osodanes jeg åbner lige igen. Det er starttagget på linje 58, som mangler et endtag: https://github.com/Clara-Kloster/Guldkorpus/blame/master/transcriptions/org/working/481.org#L58
Har du tid til at kigge på det?

**Comment by Osodanes** [comment]
Nu er den fikset :)
